- id: https://doi.org/10.1101/2023.03.16.23287381 
  tags:
  - evolution
  - poliovirus
  - student contributions
  image: https://pubmed.ncbi.nlm.nih.gov/36993386/#&gid=article-figures&pid=figure-3-uid-2
  
- id: https://doi.org/10.1038/s41467-023-35813-9
  tags:
  - tb
  - genomics
  - incarceration
  - student 1st author
  - student contributions
  image: images/paper_images/pgy_phylogeny.jpg

- id: https://academic.oup.com/ofid/article/10/2/ofad001/6974689
  publisher: OFID
  tags:
  - sars-cov-2
  - genomics
  - student contributions
  image: images/paper_images/scv-2.jpg

- id: doi:10.5588/ijtld.21.0449
  tags:
  - tb
  - incarceration
  - student 1st author
  - student contributions
  image: images/paper_images/State_DOT_access.jpg

- id: doi:10.1016/j.lana.2022.100186
  tags:
  - tb
  - incarceration
  - student contributions
  image: images/action/big_phylogeny.jpg

- id: doi:10.1093/ofid/ofab600
  tags:
  - sars-cov-2
  - genomics
  - student contributions
  image: images/paper_images/ofid_mask.png

- id: doi:10.1016/j.scitotenv.2022.156970
  tags:
  - tb
  - environmental sampling
  - student contributions
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0048969722040670-mmc3.jpg

- id: doi:10.1093/cid/ciac312
  tags:
  - sars-cov-2
  - genomics
  image: images/paper_images/favi.jpeg

- id: doi:10.1371/journal.pmed.1003789
  tags:
  - tb
  - incarceration
  - student 1st author
  - student contributions
  image: images/paper_images/mortality.jpg

- id: doi:10.1016/S2468-2667(21)00025-6
  image: https://www.thelancet.com/cms/attachment/395aa3d6-7256-48c7-945a-d667f9ca1f11/gr2.gif
  tags:
  - tb
  - incarceration

- id: doi:10.3201/eid2703.203839
  tags:
  - tb
  - incarceration
  - genomics
  - student contributions
  image: images/paper_images/tb_cluster_eid.jpeg

- id: doi:10.1016/S0140-6736(20)32578-2
  tags:
  - tb
  - incarceration
  - student contributions
  image: images/paper_images/lancet_map.jpg  

- id: doi:10.1101/2021.11.30.21266839
  image: images/paper_images/fajer_map.jpg
  tags:
  - tb
  - incarceration
  - student contributions
  - student 1st author
- id: doi:10.1007/s11538-021-00896-2
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs11538-021-00896-2/MediaObjects/11538_2021_896_Fig6_HTML.png?as=webp
  tags: 
  - within-host diversity
  - Lyme disease
  - dynamic models
- id: doi:10.1099/mgen.0.000418
  tags: 
  - tb
  - genomics
  - student contributions
  image: https://www.microbiologyresearch.org/docserver/fulltext/mgen/6/8/mgen000418-f3.gif
- id: doi:10.1183/13993003.02302-2018
  tags: 
  - tb
  image: images/paper_images/tb_environment.jpg
- id: https://doi.org/10.1371/journal.pmed.1002737
  tags: 
  - tb
  - incarceration
  image: images/paper_images/tb_incidence_mabud.jpg
- id: doi:10.1371/journal.ppat.1007470
  tags: 
  - vectors
  image: https://journals.plos.org/plospathogens/article/figure/image?size=inline&id=10.1371/journal.ppat.1007470.g005
- id: doi:10.1038/s41559-017-0282-8
  tags:
  - Lyme disease
  - vectors
  - genomics
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6431794/bin/nihms-894064-f0003.jpg
- id: doi:10.1098/rspb.2017.0901
  tags: 
  - climate change
  image: https://royalsocietypublishing.org/cms/asset/1c8fed57-f0d9-4371-bc32-b0a7e0573b58/rspb20170901f01.jpg
- id: doi:10.1186/s12864-016-3225-x
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs12864-016-3225-x/MediaObjects/12864_2016_3225_Fig1_HTML.gif?as=webp
  tags: 
  - vectors
  - genomics
- id: doi:10.1371/journal.ppat.1005759
  image: images/paper_images/within-tick.jpg
  tags: 
  - vectors
  - genomics
  - Lyme disease
  - within-host diversity
- id: doi:10.1098/rspb.2016.0834
  image: images/paper_images/lyme_map.jpg
  tags: 
  - vectors
  - Lyme disease
  - climate change 
  - dynamic models
- id: doi:10.1186/s12864-015-1634-x
  tags: 
  - vectors
  - Lyme disease
  - genomics
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs12864-015-1634-x/MediaObjects/12864_2015_1634_Fig1_HTML.gif?as=webp
- id: doi:10.1603/ME13097
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/jme/51/3/10.1603_ME13097/3/m_jmedent51-0596-fig1.jpeg?Expires=1672915485&Signature=bOq0B703kdLlIdYP0R3D~DqdpNl854Wpfh5zRi6DKm5rlL5X1rBLF1CsyezgiYdkm3ZfvdJ7gkyamrWFjrodaAh-NJqGoe-pst5Z7ksrUDSrs9TS7fD6QuI9Awzi4aGLjE4JGBZ~oZbjDo3zIynFuu9GUNvo-i8JeDZFWDDBk6cmpY~JgEj3z9yTZTwrhouhSen22Dt79GCNJfL~D-G8YW-BOeUlmdad-zTIphedPPKWIkeUZM5LmE6oNjg7ErEoMoBSZUtuzbBYxtP8SoPlQChBGbmg7dL7autQ8xgLg5zgRVaINE8hQz6fTNNOvbbOWSYWzJOLaGTNRRz-05Qh1Q__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags: 
  - vectors
- id: doi:10.1128/JVI.00256-09
  tags: 
  - HIV
  image: https://journals.asm.org/cms/10.1128/JVI.00256-09/asset/67caf011-3449-4f36-ba4c-e8276ccc33d4/assets/graphic/zjv0130920270001.jpeg